// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customWidgets from './customWidgets';

export const householdMadeLongDistanceTripsInLastYear: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.madeLongDistanceTripsInLastYear',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('longDistance:householdMadeLongDistanceTripsInLastYear', {
            count: countPersons
        });
    },
    choices: choices.yesNoDontKnow,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

// Custom because it is a map around the home
export const householdLongDistanceIntroMap = customWidgets.householdLongDistanceIntroMap;

export const householdLongDistanceTripsMayAugust: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.longDistanceTripsMayAugust',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('longDistance:householdLongDistanceTripsMayAugust', {
            count: countPersons
        });
    },
    choices: choices.longDistanceFrequencyChoices,
    conditional: conditionals.madeLongDistanceTripsConditional,
    validations: validations.requiredValidation
};

export const householdLongDistanceTripsJanuaryApril: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.longDistanceTripsJanuaryApril',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('longDistance:householdLongDistanceTripsJanuaryApril', {
            count: countPersons
        });
    },
    choices: choices.longDistanceFrequencyChoices,
    conditional: conditionals.madeLongDistanceTripsConditional,
    validations: validations.requiredValidation
};

export const householdLongDistanceTripsSeptemberDecember: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.longDistanceTripsSeptemberDecember',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('longDistance:householdLongDistanceTripsSeptemberDecember', {
            count: countPersons
        });
    },
    choices: choices.longDistanceFrequencyChoices,
    conditional: conditionals.madeLongDistanceTripsConditional,
    validations: validations.requiredValidation
};

export const wouldLikeToParticipateToLongDistanceSurvey: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.wouldLikeToParticipateToLongDistanceSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('longDistance:wouldLikeToParticipateToLongDistanceSurvey'),
    choices: choices.yesNo,
    conditional: conditionals.madeLongDistanceTripsConditional,
    validations: validations.requiredValidation
};

export const wouldLikeToParticipateToLongDistanceSurveyContactEmail: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'household.wouldLikeToParticipateToLongDistanceSurveyContactEmail',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('longDistance:wouldLikeToParticipateToLongDistanceSurveyContactEmail'),
    conditional: conditionals.wantToParticipateInLongDistanceSurveyConditional,
    validations: validations.emailValidation
};

export const buttonCompleteLongDistanceSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteLongDistanceSection',
    label: (t: TFunction) => t('longDistance:buttonCompleteLongDistanceSection'),
    conditional: defaultConditional
};
