// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';
import * as customChoices from './customChoices';

// activePersonTitle

// buttonSwitchPerson

// personTripsTitle

// personVisitedPlacesMap

// personTrips

// segmentIntro

// segments

// segmentSameModeAsReverseTrip

// segmentModePre

// segmentMode

// Custom because of the icons in the choices
export const segmentHowToBus = customWidgets.segmentHowToBus;

export const segmentPaidForParking: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'paidForParking',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('segments:segmentPaidForParking'),
    choices: choices.yesNoDontKnow,
    conditional: customConditionals.isCarDriverAndDestinationWorkCustomConditional,
    validations: validations.requiredValidation
};

export const segmentVehicleOccupancy: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'vehicleOccupancy',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('segments:segmentVehicleOccupancy'),
    valueRange: {
        min: 1,
        max: 5
    },
    overMaxAllowed: true,
    additionalChoices: choices.vehicleOccupancyExtraChoices,
    conditional: customConditionals.isCarDriverCustomConditional,
    validations: validations.requiredValidation
};

// segmentDriver

// Custom because of the choices that include available bus routes
export const segmentBusLines = customWidgets.segmentBusLines;

// Custom because of the color and size of the choices
export const segmentBusLinesWarning = customWidgets.segmentBusLinesWarning;

export const segmentOnDemandType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'onDemandType',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('segments:segmentOnDemandType'),
    choices: customChoices.onDemandCustomChoices,
    conditional: customConditionals.shouldDisplayOnDemandTypeCustomConditional,
    validations: validations.requiredValidation
};

export const tripJunctionQueryString: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'tripJunctionQueryString',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('segments:tripJunctionQueryString'),
    conditional: customConditionals.shouldAskTripJunctionCustomConditional,
    validations: validations.optionalValidation
};

// Custom because it is a map
export const tripJunctionGeography = customWidgets.tripJunctionGeography;

// segmentHasNextMode

// buttonSaveTrip

// buttonConfirmNextSection
