// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';

// activePersonTitle

// buttonSwitchPerson

// personVisitedPlacesTitle

// personVisitedPlacesMap

// personVisitedPlaces

// visitedPlaceActivityCategory

// visitedPlaceActivity

// visitedPlaceOnTheRoadPreviousPlaceActivity

// visitedPlaceAlreadyVisited

// visitedPlaceShortcut

// visitedPlaceName

// visitedPlaceGeography

// visitedPlacePreviousPreviousDepartureTime

// visitedPlacePreviousArrivalTime

// visitedPlacePreviousDepartureTime

// visitedPlaceArrivalTime

// visitedPlaceNextPlaceCategory

// visitedPlaceOnTheRoadNextPlaceCategory

// visitedPlaceDepartureTime

// buttonSaveVisitedPlace

// buttonCancelVisitedPlace

// buttonDeleteVisitedPlace

// buttonVisitedPlacesConfirmNextSection
