// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import { type ChoiceType } from 'evolution-common/lib/services/questionnaire/types';
import _escape from 'lodash/escape';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as conditionals from './conditionals';
import * as customConditionals from './customConditionals';

export const yes: ChoiceType[] = [
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:yes.yes')
    }
];

export const no: ChoiceType[] = [
    {
        value: 'no',
        label: (t: TFunction) => t('choices:no.no')
    }
];

export const other: ChoiceType[] = [
    {
        value: 'other',
        label: (t: TFunction) => t('choices:other.other')
    }
];

export const otherWithoutSpecify: ChoiceType[] = [
    {
        value: 'other',
        label: (t: TFunction) => t('choices:otherWithoutSpecify.other')
    }
];

export const dontKnow: ChoiceType[] = [
    {
        value: 'dontKnow',
        label: (t: TFunction) => t('choices:dontKnow.dontKnow')
    }
];

export const preferNotToAnswer: ChoiceType[] = [
    {
        value: 'preferNotToAnswer',
        label: (t: TFunction) => t('choices:preferNotToAnswer.preferNotToAnswer')
    }
];

export const yesNo: ChoiceType[] = [...yes, ...no];

export const yesNoDontKnow: ChoiceType[] = [...yesNo, ...dontKnow];

export const yesNoPreferNotToAnswer: ChoiceType[] = [...yes, ...no, ...preferNotToAnswer];

export const maleFemalePreferNotAnswer: ChoiceType[] = [
    {
        value: 'female',
        label: (t: TFunction) => t('choices:maleFemalePreferNotAnswer.female')
    },
    {
        value: 'male',
        label: (t: TFunction) => t('choices:maleFemalePreferNotAnswer.male')
    },
    ...preferNotToAnswer
];

export const maleFemaleCustomPreferNotToAnswer: ChoiceType[] = [
    {
        value: 'female',
        label: (t: TFunction) => t('choices:maleFemaleCustomPreferNotToAnswer.female')
    },
    {
        value: 'male',
        label: (t: TFunction) => t('choices:maleFemaleCustomPreferNotToAnswer.male')
    },
    {
        value: 'custom',
        label: (t: TFunction) => t('choices:maleFemaleCustomPreferNotToAnswer.custom')
    },
    ...preferNotToAnswer
];

export const participationStatusWorker: ChoiceType[] = [
    {
        value: 'fullTime',
        label: (t: TFunction) => t('choices:participationStatusWorker.fullTime')
    },
    {
        value: 'partTime',
        label: (t: TFunction) => t('choices:participationStatusWorker.partTime')
    },
    ...no
];

export const participationStatusStudent: ChoiceType[] = [
    {
        value: 'fullTime',
        label: (t: TFunction) => t('choices:participationStatusStudent.fullTime')
    },
    {
        value: 'partTime',
        label: (t: TFunction) => t('choices:participationStatusStudent.partTime')
    },
    ...no
];

export const schoolType: ChoiceType[] = [
    {
        value: 'kindergarten',
        label: (t: TFunction) => t('choices:schoolType.kindergarten'),
        conditional: conditionals.ifAge5OrLessConditional
    },
    {
        value: 'primarySchool',
        label: (t: TFunction) => t('choices:schoolType.primarySchool'),
        conditional: conditionals.ifAge4to13Conditional
    },
    {
        value: 'secondarySchool',
        label: (t: TFunction) => t('choices:schoolType.secondarySchool'),
        conditional: conditionals.ifAge11OrMoreConditional
    },
    {
        value: 'schoolAtHome',
        label: (t: TFunction) => t('choices:schoolType.schoolAtHome'),
        conditional: conditionals.ifAge4to15Conditional
    },
    {
        value: 'atHome',
        label: (t: TFunction) => t('choices:schoolType.atHome'),
        conditional: conditionals.ifAge5OrLessConditional
    },
    {
        value: 'collegeCegepDepAep',
        label: (t: TFunction) => t('choices:schoolType.collegeCegepDepAep'),
        conditional: conditionals.ifAge15OrMoreConditional
    },
    ...other
];

export const personOccupation: ChoiceType[] = [
    {
        value: 'fullTimeWorker',
        label: (t: TFunction) => t('choices:personOccupation.fullTimeWorker'),
        hidden: true
    },
    {
        value: 'partTimeWorker',
        label: (t: TFunction) => t('choices:personOccupation.partTimeWorker'),
        hidden: true
    },
    {
        value: 'workerAndStudent',
        label: (t: TFunction) => t('choices:personOccupation.workerAndStudent'),
        hidden: true
    },
    {
        value: 'fullTimeStudent',
        label: (t: TFunction) => t('choices:personOccupation.fullTimeStudent'),
        hidden: true
    },
    {
        value: 'partTimeStudent',
        label: (t: TFunction) => t('choices:personOccupation.partTimeStudent'),
        hidden: true
    },
    {
        value: 'retired',
        label: (t: TFunction) => t('choices:personOccupation.retired'),
        conditional: conditionals.ifAge40OrMoreConditional
    },
    {
        value: 'atHome',
        label: (t: TFunction) => t('choices:personOccupation.atHome')
    },
    {
        value: 'unemployed',
        label: (t: TFunction) => t('choices:personOccupation.unemployed')
    },
    {
        value: 'parentalOrSickLeave',
        label: (t: TFunction) => t('choices:personOccupation.parentalOrSickLeave')
    },
    {
        value: 'longTermDisability',
        label: (t: TFunction) => t('choices:personOccupation.longTermDisability')
    },
    {
        value: 'volunteer',
        label: (t: TFunction) => t('choices:personOccupation.volunteer')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:personOccupation.other')
    },
    {
        value: 'preferNotToAnswer',
        label: (t: TFunction) => t('choices:personOccupation.preferNotToAnswer')
    }
];

export const transitFareType: ChoiceType[] = [
    ...no,
    {
        value: 'transitPass',
        label: (t: TFunction) => t('choices:transitFareType.transitPass')
    },
    {
        value: 'tickets',
        label: (t: TFunction) => t('choices:transitFareType.tickets')
    },
    ...dontKnow
];

export const workPlaceTypeChoices: ChoiceType[] = [
    {
        value: 'onLocation',
        label: (t: TFunction) => t('choices:workPlaceTypeChoices.onLocation')
    },
    {
        value: 'hybrid',
        label: (t: TFunction) => t('choices:workPlaceTypeChoices.hybrid')
    },
    {
        value: 'onTheRoadWithUsualPlace',
        label: (t: TFunction) => t('choices:workPlaceTypeChoices.onTheRoadWithUsualPlace')
    },
    {
        value: 'onTheRoadWithoutUsualPlace',
        label: (t: TFunction) => t('choices:workPlaceTypeChoices.onTheRoadWithoutUsualPlace')
    },
    {
        value: 'remote',
        label: (t: TFunction) => t('choices:workPlaceTypeChoices.remote')
    }
];

export const schoolPlaceTypeChoices: ChoiceType[] = [
    {
        value: 'onLocation',
        label: (t: TFunction) => t('choices:schoolPlaceTypeChoices.onLocation')
    },
    {
        value: 'hybrid',
        label: (t: TFunction) => t('choices:schoolPlaceTypeChoices.hybrid')
    },
    {
        value: 'remote',
        label: (t: TFunction) => t('choices:schoolPlaceTypeChoices.remote')
    }
];

export const longDistanceFrequencyChoices: ChoiceType[] = [
    {
        value: '00_00',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.00_00')
    },
    {
        value: '01_03',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.01_03')
    },
    {
        value: '04_12',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.04_12')
    },
    {
        value: '13_99',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.13_99')
    }
];

export const householdIncomeChoices: ChoiceType[] = [
    {
        value: '000000_014999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.000000_014999')
    },
    {
        value: '015000_029999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.015000_029999')
    },
    {
        value: '030000_044999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.030000_044999')
    },
    {
        value: '045000_059999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.045000_059999')
    },
    {
        value: '060000_079999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.060000_079999')
    },
    {
        value: '080000_099999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.080000_099999')
    },
    {
        value: '100000_149999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.100000_149999')
    },
    {
        value: '150000_199999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.150000_199999')
    },
    {
        value: '200000_999999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.200000_999999')
    },
    {
        value: 'dontKnow',
        label: (t: TFunction) => t('choices:householdIncomeChoices.dontKnow')
    },
    {
        value: 'refusal',
        label: (t: TFunction) => t('choices:householdIncomeChoices.refusal')
    }
];

export const householdOwnershipChoices: ChoiceType[] = [
    {
        value: 'tenant',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.tenant')
    },
    {
        value: 'owner',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.owner')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.other')
    },
    {
        value: 'preferNotToAnswer',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.preferNotToAnswer')
    }
];

export const departurePlaceOtherChoices: ChoiceType[] = [
    {
        value: 'otherParentHome',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.otherParentHome'),
        conditional: conditionals.ifAge16OrLessConditional
    },
    {
        value: 'workedOvernight',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.workedOvernight'),
        conditional: conditionals.isWorkerConditional
    },
    {
        value: 'secondaryHome',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.secondaryHome')
    },
    {
        value: 'sleptAtFriends',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.sleptAtFriends')
    },
    {
        value: 'restaurant',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.restaurant')
    },
    {
        value: 'hotelForWork',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.hotelForWork'),
        conditional: conditionals.isWorkerConditional
    },
    {
        value: 'hotelForVacation',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.hotelForVacation')
    },
    {
        value: 'studying',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.studying'),
        conditional: conditionals.isStudentConditional
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.other')
    }
];

export const onTheRoadArrivalTypeChoices: ChoiceType[] = [
    {
        value: 'home',
        label: (t: TFunction) => t('choices:onTheRoadArrivalTypeChoices.home')
    },
    {
        value: 'usualWorkPlace',
        label: (t: TFunction) => t('choices:onTheRoadArrivalTypeChoices.usualWorkPlace'),
        conditional: conditionals.onTheRoadUsualWorkplace
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:onTheRoadArrivalTypeChoices.other')
    },
    {
        value: 'stayedThereUntilTheNextDay',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:onTheRoadArrivalTypeChoices.stayedThereUntilTheNextDay', {
                nickname,
                count: countPersons,
                context: activePerson?.gender || activePerson?.sexAssignedAtBirth
            });
        },
        conditional: customConditionals.isLastPlaceCustomConditional
    }
];

export const onDemandChoices: ChoiceType[] = [
    {
        value: 'pickupAtOrigin',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:onDemandChoices.pickupAtOrigin', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'joinedStop',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:onDemandChoices.joinedStop', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'no',
        label: (t: TFunction) => t('choices:onDemandChoices.no')
    }
];

export const noWorkTripReasonChoices: ChoiceType[] = [
    {
        value: 'remoteWorkOrWorkAtHome',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.remoteWorkOrWorkAtHome')
    },
    {
        value: 'onStrike',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.onStrike')
    },
    {
        value: 'leaveSicknessPersonalReason',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.leaveSicknessPersonalReason')
    },
    {
        value: 'noWork',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.noWork')
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const noSchoolTripReasonChoices: ChoiceType[] = [
    {
        value: 'distanceLearning',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.distanceLearning')
    },
    {
        value: 'schoolWasClosed',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.schoolWasClosed')
    },
    {
        value: 'leaveSicknessPersonalReason',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.leaveSicknessPersonalReason')
    },
    {
        value: 'noSchool',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.noSchool')
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const educationalAttainment: ChoiceType[] = [
    {
        value: 'noneOrPrimaryEducation',
        label: (t: TFunction) => t('choices:educationalAttainment.noneOrPrimaryEducation')
    },
    {
        value: 'secondaryEducation',
        label: (t: TFunction) => t('choices:educationalAttainment.secondaryEducation')
    },
    {
        value: 'postSecondaryNonTertiaryEducation',
        label: (t: TFunction) => t('choices:educationalAttainment.postSecondaryNonTertiaryEducation')
    },
    {
        value: 'shortCycleTertiaryEducation',
        label: (t: TFunction) => t('choices:educationalAttainment.shortCycleTertiaryEducation')
    },
    {
        value: 'diplomaBelowBachelor',
        label: (t: TFunction) => t('choices:educationalAttainment.diplomaBelowBachelor')
    },
    {
        value: 'bachelorOrHigher',
        label: (t: TFunction) => t('choices:educationalAttainment.bachelorOrHigher')
    },
    ...preferNotToAnswer
];

export const workPlaceBeforeLeaveTypeChoices: ChoiceType[] = [
    {
        value: 'onLocation',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.onLocation', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'hybrid',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.hybrid', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'onTheRoadWithUsualPlace',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.onTheRoadWithUsualPlace', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'onTheRoadWithoutUsualPlace',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.onTheRoadWithoutUsualPlace', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'remote',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.remote', {
                nickname,
                count: countPersons
            });
        }
    }
];

export const vehicleOccupancyExtraChoices: ChoiceType[] = [
    {
        value: 'dontKnow',
        label: (t: TFunction) => t('choices:vehicleOccupancyExtraChoices.dontKnow'),
        conditional: customConditionals.isProxyCustomConditional
    }
];
